Optimize correctness workflow
Only clone the repository and install node.js dependencies
once instead of three separate times

diff --git a/.github/workflows/check-locales-format.yml b/.github/workflows/check-locales-format.yml
--- a/.github/workflows/check-locales-format.yml
+++ b/.github/workflows/check-locales-format.yml
@@ -1,82 +1,84 @@
-name: Validate locales formats
+name: Validate locales files for correctness
 on:
-    # adjust for Pokerogue
-    pull_request:
-        branches:
-            - main
-    push:
-        branches:
-            - main
+  # adjust for Pokerogue
+  pull_request:
+    branches:
+      - main
+  push:
+    branches:
+      - main
 
 jobs:
-    validate-locale-keys:
-        name: Validate locale keys
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v5
+  validate-locales-files:
+    name: Validate locales files
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
 
-            - name: Install pnpm
-              uses: pnpm/action-setup@v4
-              with:
-                  version: 10
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
+        with:
+          version: 10
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v4
-              with:
-                node-version: 22.14.0
-                cache: "pnpm"
-            
-            - name: Install Node.js dependencies
-              run: pnpm add @actions/core
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22.14.0
+          cache: "pnpm"
+      
+      - name: Install Node.js dependencies
+        run: pnpm add @actions/core
 
-            - name: Validate locale keys
-              run: pnpm check-locales-format:keys
+      - name: Validate locale keys
+        id: check-keys-format
+        run: pnpm check-locales-format:keys
+        continue-on-error: true
 
-    validate-locale-file-names:
-        name: Validate locale file names
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v5
+      - name: Validate locale file names
+        id: check-file-names
+        run: pnpm check-locales-format:files
+        continue-on-error: true
 
-            - name: Install pnpm
-              uses: pnpm/action-setup@v4
-              with:
-                  version: 10
+      - name: Validate main language keys exist
+        id: check-keys-exist
+        run: pnpm check-locales-format:missing
+        continue-on-error: true
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v4
-              with:
-                node-version: 22.14.0
-                cache: "pnpm"
-            
-            - name: Install Node.js dependencies
-              run: pnpm add @actions/core
+      - name: Evaluate for Errors
+        env:
+          CHECK_KEYS_FORMAT_OUTCOME: ${{ steps.check-keys-format.outcome }}
+          CHECK_FILE_NAMES_OUTCOME: ${{ steps.check-file-names.outcome }}
+          CHECK_KEYS_EXIST_OUTCOME: ${{ steps.check-keys-exist.outcome }}
+        run: |
+          # Script to check for errors
 
-            - name: Validate locale file names
-              run: pnpm check-locales-format:files
+          red () {
+            printf "\e[31m%s\e[0m" "$1"
+          }
+          green () {
+            printf "\e[32m%s\e[0m" "$1"
+          }
 
-    validate-main-keys-exist:
-        name: Validate main language keys exist
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v5
+          print_result() {
+            local name=$1
+            local outcome=$2
+            if [ "$outcome" == "success" ]; then
+              printf "$(green "✅ $name: $outcome")\n"
+            else
+              printf "$(red "❌ $name: $outcome")\n"
+            fi
+          }
 
-            - name: Install pnpm
-              uses: pnpm/action-setup@v4
-              with:
-                  version: 10
+          print_result "Check Keys Format" "$CHECK_KEYS_FORMAT_OUTCOME"
+          print_result "Check File Names" "$CHECK_FILE_NAMES_OUTCOME"
+          print_result "Check Keys Exist" "$CHECK_KEYS_EXIST_OUTCOME"
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v4
-              with:
-                node-version: 22.14.0
-                cache: "pnpm"
-            
-            - name: Install Node.js dependencies
-              run: pnpm add @actions/core
+          if [[ "$CHECK_KEYS_FORMAT_OUTCOME" != "success" || \
+            "$CHECK_FILE_NAMES_OUTCOME" != "success" || \
+            "$CHECK_KEYS_EXIST_OUTCOME" != "success" ]]; then
+            printf "$(red "❌ One or more checks failed!")\n" >&2
+            exit 1
+          fi
 
-            - name: Validate main language keys exist
-              run: pnpm check-locales-format:missing
+          printf "$(green "✅ All checks passed!")\n"
